version: 2
jobs:
  build:
    docker:
      - image: tmcgilchrist/ci-ocaml:ubuntu_xenial-4.04

    steps:
      - checkout

      # TODO(shon): This shouldn't be necessary, as dune is supposed to be
      # on this container already
      - run:
          name: Install Dune
          command: opam install dune

      - run:
          name: Install Package Dependencies
          command: opam install . --deps-only -y

      - run:
          name: Install Testing Dependencies
          command: opam install qcheck alcotest qcheck-alcotest -y

      - run:
          name: Build
          command: dune build

      - run:
          name: Run tests
          command: dune runtest
