version: 2

jobs:
  build:
    docker:
      - image: shonfeder/ocaml-ci-docker

    steps:
      - checkout

      - restore_cache:
          keys:
            - opam-cache-{{ checksum "ocobs.opam" }}

      - run:
          name: Create OPAM Switch
          # Also installs all project dependencies
          command: |
            export TERM=dumb
            eval $(opam env)
            # If the switch creation fails, assume it's because it already exists
            opam switch create . 4.07.1 --yes --with-test || true

      # NOTE We must dump the dune rules after installing the package
      # dependencies, since Successful runs of `dune rules` may depend on
      # package dependencies, e.g., for ppx preprocessors.
      - run:
          name: Dump dune Rules
          command: |
            eval $(opam env)
            dune rules > /tmp/dune-rules

      - restore_cache:
          keys:
            - dune-cache-{{ checksum "/tmp/dune-rules" }}

      - run:
          name: Run tests
          command: |
            eval $(opam env)
            dune runtest

      - save_cache:
          key: dune-cache-{{ checksum "/tmp/dune-rules" }}
          paths:
            - _build

      - save_cache:
          key: opam-cache-{{ checksum "ocobs.opam" }}
          paths:
            - _opam

