version: 2
jobs:
  build:
    docker:
      - image: shonfeder/ocaml-ci-docker

    steps:
      - checkout

      - run:
          name: Install Package Dependencies
          command: opam install . --with-test -y

      - run:
          name: Run tests
          command: |
            eval $(opam env)
            dune runtest
